### ISSUE TITLE
difference to storeBackup?

### ISSUE THREAD

**Issue by 517qf** [paulbearddotname/lnbackup#1]
Thanks for sharing your script. It looks really good.

I just discovered a tool named [storeBackup](http://storebackup.org/) which is also an improved version of rsnapshot by using md5 checksums to identify renamed or moved files and a [bunch of other features](http://www.nongnu.org/storebackup/en/node2.html) like fine grained inclusion/exclusion rules.

Maybe you have seen this tool before you decided to create lnbackup. Many people only write code to "scratch an itch" so maybe you found a problem in storeBackup that disqualifies it for you? If so, maybe you could share it because at the moment I'm leaning towards storeBackup because it seems to be a more mature project. (But maybe you just wanted to create something of your own wich is also a very good reason). 

Again: thanks sharing your project!

**Comment by paulbearddotname** [comment]
Hi,

Yes I was scratching an itch. I knew of rsnapshot but had no intention of using it. I wanted to write my own backup scripts and I had a few specific requirements:

- The layout of the backup directories should be the same as the source. I wanted to be able to restore from backup, with nothing more than a file manager.
- The backup directories should be pruned in the same was as Apple TimeMachine backups.
- The complexity of the backup script must be low and the feature set minimal. The less code I write, the fewer bugs I create.

I wrote two such scripts. This one, and another called [rsyncbackup](https://github.com/paulbearddotname/rsyncbackup).

[rsyncbackup](https://github.com/paulbearddotname/rsyncbackup) is a light wrapper around rsync that makes extensive use of the --link-dest option, and adds the backup pruning behaviour.

If you want a something more stable, I'd suggest having a look at [rsyncbackup](https://github.com/paulbearddotname/rsyncbackup).

**Comment by 517qf** [comment]
Thanks a lot for your answer. 

As a noob I underestimated this:

> The complexity of the backup script must be low and the feature set minimal. The less code I write, the fewer bugs I create.

The other backup software that I mentioned (named storeBackup) seems to depend on about 15k lines only for creating backups.  That's too long for me whereas I can check all of your 300 lines. So I'll download yours.
